version: '3'

services:
  api-service:
    build:
      context: .
      dockerfile: docker/Dockerfile-dev
    container_name: service
    ports:
      - '80:80'
    volumes: 
      - ./:/go/src/kevinjon27/service
    command: ["air", "-c", "watcher.conf"]