version: '3'

services:
  go-service:
    build:
      context: .
      dockerfile: docker/Dockerfile-dev
    container_name: go-container
    ports:
      - '80:80'
    volumes: 
      - ./:/go/src/kevinjon27/golang-docker-boilerplate
    command: ["air", "-c", "air.toml"]