FROM golang@sha256:e484434a085a28801e81089cc8bcec65bc990dd25a070e3dd6e04b19ceafaced AS builder

RUN apk update && \
    apk add --no-cache git ca-certificates tzdata bash curl && \
    update-ca-certificates

RUN go get -u github.com/cosmtrek/air

WORKDIR $GOPATH/src/kevinjon27/golang-docker-boilerplate/
COPY . .

EXPOSE 80
